### ISSUE TITLE
when build loads, it automatically goes to the last block

### ISSUE THREAD

**Issue by RosiniB** [BATraining/adapt-embeddedLink#32]
i created a small build with 4 blocks (all were using the embeddedLink component)
2 first one were set to true and 2 last ones were set to false.

When the build generates and i get my preview load, it automatically goes to the last block:
http://staging.batraining.com/Adapt/workPack6/#/id/co-05

**Comment by akshay-bhavsar** [comment]
Hi @RosiniB :
Thanks for the update. We have replicated the above issue at our end, while debugging the issue we do realise that this issue have no relation with the completion of component. Actually the site which we are loading that is (http://www.bing.com) has it's own property of getting focused on loading and adapt loads the blocks from top to bottom therefore the last block having link get focused.
We have tried youtube link instead of bing and it's working appropriately.  Can you please try with any other link than bing, for example: (https://www.youtube.com/embed/5a5S682J1R8) (which we have been tried.)
Please verify and confirm if this works and let us know your suggestion on the same.
Thanks!

**Comment by RosiniB** [comment]
thanks for the validation, it works as expected now with the suggestion.
